function(module_def MODULE_NAME URL OPTIONS DESCRIPTION)
	set(MODULES_${MODULE_NAME} false CACHE BOOL ${DESCRIPTION})
	if(MODULES_${MODULE_NAME})
		if(${OPTIONS} STREQUAL NATIVE)
			message("MODULE ${MODULE_NAME} IS NATIVE")
			execute_process(COMMAND ${GIT_EXECUTABLE} clone ${URL} ${CMAKE_SOURCE_DIR}/modules/native/${MODULE_NAME})
		else()
			message("MODULE ${MODULE_NAME} IS SCRIPT")
			execute_process(COMMAND ${GIT_EXECUTABLE} clone ${URL} ${CMAKE_SOURCE_DIR}/modules/${MODULE_NAME})
		endif()
	endif()
endfunction()