function(module_def MODULE_NAME URL OPTIONS DESCRIPTION)
	set(MODULES_${MODULE_NAME} false CACHE BOOL ${DESCRIPTION})
	if(MODULES_${MODULE_NAME})
		if(${OPTIONS} STREQUAL NATIVE)
			message("MODULE ${MODULE_NAME} is NATIVE")
			execute_process(COMMAND ${GIT_EXECUTABLE} clone ${URL} ${CMAKE_SOURCE_DIR}/modules/${MODULE_NAME})
			file(APPEND ${MODULES_CMAKE_FILE} "add_subdirectory(${MODULE_NAME})\n")
			file(APPEND ${MODULES_CONFIG_FILE} "#define ${MODULE_NAME}_ENABLED\n")
		else()
			message("MODULE ${MODULE_NAME} is SCRIPT")
			execute_process(COMMAND ${GIT_EXECUTABLE} clone ${URL} ${CMAKE_SOURCE_DIR}/modules/${MODULE_NAME})
		endif()
	endif()
endfunction()